# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0018_auto_20160513_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='dupefilter_unnecessary_urls',
            field=models.TextField(blank=True),
        ),
    ]
